app = "minecraft-web-client"
primary_region = "sjc"

[build]

[env]
  PORT = "8080"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

[[vm]]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1
